apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: CloudQuest
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://customer-service:IZADeiXJCi8RFrG4@customer-service-db.qgarx.mongodb.net"
  PORT: "5000"
  JWT_SECRET: "8191b23e5620ff667af0439f75d55452a823fecc45461c3ae424e409a509da04"
  NODE_ENV: "production"
  MAILTRAP_TOKEN: "e8c2b73f9f187d7f4c2d62cbc9d4afbe"
  MAILTRAP_ENDPOINT: "https://send.api.mailtrap.io/"
  CLIENT_URL: "https://major1cloudquest.cloud/"