apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: CloudQuest
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: 407622020962.dkr.ecr.us-east-1.amazonaws.com/frontend:1
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL # The URL for your backend – VERY IMPORTANT
            value: "https://major1cloudquest.cloud/api/auth" # Updated path
        ports:
        - containerPort: 5173
